### PR TITLE
Example config/colclasure20

### PR DESCRIPTION
**Pull request by d-cogswell**
Implements the low loading NMC532/graphite model from this paper: https://dx.doi.org/10.1016/j.electacta.2020.135854

I can get a match to the 2C charging simulation, but I could not find solid conductivity in the paper, which probably affects the match at higher currents. I emailed Andrew about this.

Remaining items:
- Add a regression test when the new test suite is ready

### CODE REVIEW

**Comment by lightningclaw001** [comment]
Can we merge the electrolyte activity into the electrolyte function (into thermfac) so we can just have the Colclasure model as an SM type? I will add a commit that does this.

**Comment by d-cogswell** [comment]
> Can we merge the electrolyte activity into the electrolyte function (into thermfac) so we can just have the Colclasure model as an SM type? I will add a commit that does this.

Oh, is that what therm_fac is for? That seems like the way to do it.

**Comment by lightningclaw001** [comment]
Yeah, I think it is. thermfac = 1 + dlnf/dlnc actually. :)

**Comment by lightningclaw001** [comment]
Also, in Andrew's email to us I think he said the Bruggeman coeff was 2.4 which matches what's on here, but on the paper I think the range is 2-2.2. Do you think this makes a difference?

**Comment by d-cogswell** [comment]
Will add a regression test after the temperature branch is merged.

**Pull request merged**
