### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by d-cogswell**
- Removes unused functions
- Removes deprecated logPad option and 'ISfuncs' argument
- Removes unused commented code

### CODE REVIEW

**Comment by lightningclaw001** [comment]
@d-cogswell why was Li_ss.py removed? I've used it for testing before and found it useful.

**Comment by lightningclaw001** [comment]
@d-cogswell is there a particular reason why we're removing logpad? I thought it was helpful when concentration is close to 0 or 1.

**Comment by d-cogswell** [comment]
> @d-cogswell why were the lithium metal and regular solution models removed? I've used them for testing before and found them useful.

I was looking for code that wasn't covered by the regression tests. 'testRS.py' is still there as an example of a regular solution. I thought it was weird to have a lithium OCV since it's not an intercalation material. None of the particle models would make sense.

**Comment by lightningclaw001** [comment]
> > @d-cogswell why were the lithium metal and regular solution models removed? I've used them for testing before and found them useful.
> 
> I was looking for code that wasn't covered by the regression tests. 'testRS.py' is still there as an example of a regular solution. I thought it was weird to have a lithium OCV since it's not an intercalation material. None of the particle models would make sense.

I agree that they don't make sense, but I feel like they're helpful for testing--maybe we should keep them? All the other changes look fine to me.

**Comment by d-cogswell** [comment]
> @d-cogswell is there a particular reason why we're removing logpad? I thought it was helpful when concentration is close to 0 or 1.

A better solution is to bring the log terms through the gradient operators and convert to a diffusion term, which is faster to evaluate and more numerically stable. The external function evaluation for daetools also seemed particularly slow.

**Review by lightningclaw001 — APPROVED** [review]

**Pull request merged**
