### PR TITLE
v0.1.9

### PR DESCRIPTION
**Pull request by d-cogswell**
It's time for a maintenance update before we work on some bigger pull requests. Is there anything else you'd like to include?

### CODE REVIEW

**Comment by lightningclaw001** [comment]
@d-cogswell @loostrum should we fix the numpy and the python new version errors first, push this request, and then we can work on the nonisothermal branch and cycling branch? I think some of the visiting students want to use the nonisothermal branch, and the cycling branch is currently being used by a couple in the Bazant lab including Harry and myself, so maybe we can try and put them in the newer versions.

**Comment by d-cogswell** [comment]
@lightningclaw001 yes we should fix the numpy issue, it's causing the automated tests to fail. Also now that daetools is under development again, we should test it with Python 3.10.

**Comment by lightningclaw001** [comment]
@d-cogswell just tested on linux with the new version of daetools--seems to be working fine.

**Comment by d-cogswell** [comment]
@lightningclaw001 also looks good to me, I tested in Linux and Windows.

**Review by loostrum — APPROVED** [review]
Looks like a nice set of changes for the next release, I have nothing else that I'd like to include. 
You may have noticed we opened a PR for the work in the feature/solid branch as well. That one contains most of the work we did for the Delft team. It's pretty big, so let's keep it for the next release. If you have time at some point to have a look at those changes that would be great. We can then see if we just merge it all, or if you want only certain parts of it in the main MPET code. In any case, we're rounding up the project from our side, but we'd still like to make sure any useful features make it into the main MPET code.

**Review by lightningclaw001 — APPROVED** [review]

**Pull request merged**
